### ISSUE TITLE
Generic Images with MPI

### ISSUE THREAD

**Issue by cc-a** [glotzerlab/software#134]
## Description

Rather than publishing a single platform independent image built without MPI would you consider having two generic images, one each for openmpi and mpich-compatible ABIs?

## Additional context

Firstly, I thoroughly appreciate your efforts to provide containers for your software. I recently helped a user to deploy hoomd-blue with mpi support to our local system. This required adding an additional configuration to your build system that was effectively just the nompi image + mvapich. This was pretty easy once I poked around your build system but would have been obviated if an image already existed.

**Comment by joaander** [comment]
I don't think such a generic MPI image would be functional.

In my testing on all the supported systems, I find that not only do I need to match the exact version of MPI, I also need to match a majority of the MPI compile flags used on that system. If these do not match, the host level MPI runner is not able to communicate with the MPI run time inside the container and the application either crashes on launch or ignores the MPI configuration and runs as independent processes. I have tried and not succeeded to produce one MPI enabled image that works on all HPC systems I test on.

I agree that the build system for these containers is not simple to modify, but the alternative is to build HOOMD and other packages native on the system and use them without singularity. Unless you need the LLVM support in HOOMD, that path requires less time and effort than building a customized container image.
