### ISSUE TITLE
Test signac and signac-flow

### ISSUE THREAD

**Issue by joaander** [glotzerlab/software#19]
## Description

The build should run signac and signac-flow unit tests.

## Additional context

This would ensure that the installations function inside the container.

**Comment by joaander** [comment]
@b-butler, you are more familiar with signac's testing framework than I am. Could you add the tests to `template/test.jinja` for singac, signac-flow, and signac-dashboard? Please add to the open draft PR: #147

**Comment by b-butler** [comment]
@joaander will add.

**Comment by b-butler** [comment]
@joaander how do you deal with test dependencies?

**Comment by joaander** [comment]
I haven't had a need for test dependencies yet. If the dependencies are not large, there is no harm in adding them to the install in general. Otherwise, you could use the package manager to both install and remove the dependencies in the same Docker `RUN` command.

**Comment by joaander** [comment]
Completed in #147.
