### ISSUE TITLE
Install PyTables

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/software#2]
Version 1.0.0 of signac relies on [PyTables](https://www.pytables.org) to store and load pandas data frames in HDF5 files. Would it be possible to add PyTables to the collection of commonly installed software?

**Comment by joaander** [comment]
Yes. Have you tested the pip installation into the virtual environment on summit?

**Comment by csadorf** [comment]
> Yes. Have you tested the pip installation into the virtual environment on summit?

Sorry, I didn't get to that yet, but I would expect it to work.

**Comment by joaander** [comment]
It builds and `python -c import tables` runs without error.
