### ISSUE TITLE
Can't install signac-flow on Summit

### ISSUE THREAD

**Issue by bdice** [glotzerlab/software#3]
https://github.com/glotzerlab/software/blob/47d13b563c902d6c7e53f311aa11fbaa60fff0d4/script/summit/install.sh#L148

This line fails on Summit, which seems to have been introduced by #1 in commit d54f8b26453d9a46dc2f89d0c86f6fbdfedf5545. This failure prevents HOOMD from installing (since it's installed after signac-flow).

Error:
```
signac-flow-v0.6.4.tar.gz: OK
Processing ./signac-flow-v0.6.4
Installing collected packages: signac-flow
  Running setup.py install for signac-flow ... done
Successfully installed signac-flow-0.6.4
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
chmod: cannot access '/usr/local/lib/**/dist-packages/flow/templates/*': No such file or directory
```

**Comment by csadorf** [comment]
I have a fix for that. I'll create a PR.
