### ISSUE TITLE
Update Python to version 3.6

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/software#6]
I've grown accustomed to a few features offered by Python 3.6, especially formatting-strings. Would it be possible to update the image to Python 3.6?

**Comment by joaander** [comment]
Yes, ubuntu18.04 has python 3.6.

**Comment by joaander** [comment]
I am not able to deploy the ubuntu18.04 images at this time.

- Flux: CUDA 9.2 capable drivers required
- Comet: Newer Linux kernel required
- Bridges: Allocation hours required to test image
- Stampede2: No issues

**Comment by csadorf** [comment]
Ok, thank you for trying!

**Comment by joaander** [comment]
Flux will be upgraded next week. The Comet OS upgrade is planned, but not scheduled.

Would it be useful to have python 3.6 some systems, and python3.5 on comet?

**Comment by csadorf** [comment]
I'm not sure, but I believe consistency across platforms might trump here.

**Comment by joaander** [comment]
All systems now use ubuntu 18.04 as the base image.
